global:
 message: welcome to customer-service dev environment
server:
 port:8082
message: hello from dev
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/customer-servicedev
  username: root
  password:
jpa:
 hilbernate:
  ddl-auto: update
show-sql: true
