global:
 message: welcome to customer-service prod environment
server:
 port:8083
message: hello from dev
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/customer-serviceprod
  username: root
  password:
jpa:
 hilbernate:
  ddl-auto: update
show-sql: true
