global:
 message: welcome to order-service prod environment
server:
 port:8085
message: hello from prod
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/order-serviceprod
  username: root
  password:
jpa:
 hilbernate:
  ddl-auto: update
show-sql: true
